// ============================================================================
// UFSM - Universal Finite State Machine System for Unity
// Phase 4: Code Generator - Auto-generates C# from FSM Definitions
// File: Assets/UFSM/Editor/CodeGeneration/FSMCodeGenerator.cs
// ============================================================================

using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UFSM.Runtime;
using UFSM.Core;

namespace UFSM.Editor.CodeGeneration
{
    /// <summary>
    /// Generates C# code from FSM Definitions
    /// </summary>
    public static class FSMCodeGenerator
    {
        private const string GENERATED_ROOT = "Assets/Generated";

        /// <summary>
        /// Generate all code for an FSM
        /// </summary>
        public static bool GenerateCode(FSMDefinition fsm, bool showDialog = true)
        {
            if (fsm == null)
            {
                Debug.LogError("Cannot generate code: FSM is null");
                return false;
            }

            try
            {
                string fsmFolder = Path.Combine(GENERATED_ROOT, fsm.MachineName);

                // Create directories
                Directory.CreateDirectory(fsmFolder);
                Directory.CreateDirectory(Path.Combine(fsmFolder, "States"));

                // Generate files
                GenerateContext(fsm, fsmFolder);
                GenerateStateMachine(fsm, fsmFolder);
                GenerateStates(fsm, fsmFolder);

                // Refresh asset database
                AssetDatabase.Refresh();

                if (showDialog)
                {
                    EditorUtility.DisplayDialog("Code Generated",
                        $"Successfully generated code for '{fsm.MachineName}'\n\nLocation: {fsmFolder}",
                        "OK");
                }

                Debug.Log($"[Code Generator] Generated code for FSM '{fsm.MachineName}' at {fsmFolder}");
                return true;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[Code Generator] Failed to generate code: {e.Message}\n{e.StackTrace}");

                if (showDialog)
                {
                    EditorUtility.DisplayDialog("Code Generation Failed",
                        $"Error: {e.Message}",
                        "OK");
                }

                return false;
            }
        }

        /// <summary>
        /// Generate Context class
        /// </summary>
        private static void GenerateContext(FSMDefinition fsm, string outputFolder)
        {
            string className = $"{fsm.MachineName}Context";
            string filePath = Path.Combine(outputFolder, $"{className}.cs");

            // Check if user file exists
            string userFilePath = Path.Combine(outputFolder, $"{className}.User.cs");
            bool hasUserFile = File.Exists(userFilePath);

            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// ============================================================================");
            sb.AppendLine($"// AUTO-GENERATED CODE - DO NOT EDIT THIS FILE");
            sb.AppendLine($"// FSM: {fsm.MachineName}");
            sb.AppendLine($"// Generated: {System.DateTime.Now}");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UFSM.Core;");
            sb.AppendLine("using UFSM.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Context for {fsm.MachineName} FSM");
            sb.AppendLine($"    /// Contains all data and parameters for this state machine");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public partial class {className} : ContextBase");
            sb.AppendLine("    {");

            // Parameters as properties
            if (fsm.Parameters.Count > 0)
            {
                sb.AppendLine("        // FSM Parameters");
                foreach (var param in fsm.Parameters)
                {
                    string type = GetCSharpType(param.Type);
                    string defaultValue = GetDefaultValue(param);

                    sb.AppendLine($"        public {type} {param.Name} {{ get; set; }} = {defaultValue};");
                }
                sb.AppendLine();
            }

            // Constructor
            sb.AppendLine("        public " + className + "(GameObject owner) : base(owner)");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public override void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            base.Initialize();");
            sb.AppendLine("            // Initialize context here");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());

            // Create user file if it doesn't exist
            if (!hasUserFile)
            {
                CreateUserContextFile(fsm, outputFolder, className);
            }
        }

        private static void CreateUserContextFile(FSMDefinition fsm, string outputFolder, string className)
        {
            string userFilePath = Path.Combine(outputFolder, $"{className}.User.cs");

            var sb = new StringBuilder();
            sb.AppendLine("// ============================================================================");
            sb.AppendLine($"// USER CODE - SAFE TO EDIT");
            sb.AppendLine($"// FSM: {fsm.MachineName}");
            sb.AppendLine($"// Add your custom context logic here");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        // Add your custom fields, properties, and methods here");
            sb.AppendLine("        ");
            sb.AppendLine("        // Example:");
            sb.AppendLine("        // public float CustomSpeed { get; set; } = 10f;");
            sb.AppendLine("        ");
            sb.AppendLine("        // public void CustomMethod()");
            sb.AppendLine("        // {");
            sb.AppendLine("        //     // Your code");
            sb.AppendLine("        // }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(userFilePath, sb.ToString());
        }

        /// <summary>
        /// Generate StateMachine class
        /// </summary>
        private static void GenerateStateMachine(FSMDefinition fsm, string outputFolder)
        {
            string className = $"{fsm.MachineName}StateMachine";
            string contextName = $"{fsm.MachineName}Context";
            string filePath = Path.Combine(outputFolder, $"{className}.cs");

            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// ============================================================================");
            sb.AppendLine($"// AUTO-GENERATED CODE - DO NOT EDIT THIS FILE");
            sb.AppendLine($"// FSM: {fsm.MachineName}");
            sb.AppendLine($"// Generated: {System.DateTime.Now}");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UFSM.Core;");
            sb.AppendLine("using UFSM.Runtime;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// State Machine for {fsm.MachineName}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public partial class {className} : StateMachineBase<{contextName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string MachineName => \"{fsm.MachineName}\";");
            sb.AppendLine();

            // Constructor
            sb.AppendLine($"        public {className}({contextName} context) : base()");
            sb.AppendLine("        {");
            sb.AppendLine("            Context = context;");
            sb.AppendLine("            context.StateMachine = this;");
            sb.AppendLine("            ");
            sb.AppendLine("            // Configure FSM settings");
            sb.AppendLine($"            TransitionUpdateMode = UpdateMode.{fsm.TransitionUpdateMode};");
            sb.AppendLine($"            TransitionCheckInterval = {fsm.TransitionCheckInterval}f;");
            sb.AppendLine($"            Profile = PerformanceProfile.{fsm.PerformanceProfile};");
            sb.AppendLine($"            Priority = {fsm.Priority};");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Setup method
            sb.AppendLine("        public void Setup()");
            sb.AppendLine("        {");
            sb.AppendLine("            Initialize();");
            sb.AppendLine("            ");
            sb.AppendLine("            // Register parameters");

            foreach (var param in fsm.Parameters)
            {
                string type = $"ParameterType.{param.Type}";
                string defaultVal = GetDefaultValue(param);
                sb.AppendLine($"            parameterStore.AddParameter(\"{param.Name}\", {type}, {defaultVal});");
            }

            sb.AppendLine("            ");
            sb.AppendLine("            // Register states");

            foreach (var state in fsm.States)
            {
                sb.AppendLine($"            RegisterState(new {state.StateName}State {{ Context = Context }});");
            }

            sb.AppendLine("            ");
            sb.AppendLine("            // Register transitions");

            foreach (var trans in fsm.Transitions)
            {
                string fromState = string.IsNullOrEmpty(trans.FromState) ? "\"\"" : $"\"{trans.FromState}\"";
                sb.AppendLine($"            RegisterTransition(CreateTransition({fromState}, \"{trans.ToState}\", {trans.Priority}, {trans.CanInterrupt.ToString().ToLower()}, {trans.TransitionDelay}f));");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            // Helper method to create transitions
            sb.AppendLine($"        private ITransition<{contextName}> CreateTransition(string from, string to, int priority, bool canInterrupt, float delay)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var transition = new TransitionBase<{contextName}>(from, to)");
            sb.AppendLine("            {");
            sb.AppendLine("                Priority = priority,");
            sb.AppendLine("                CanInterrupt = canInterrupt,");
            sb.AppendLine("                TransitionDelay = delay,");
            sb.AppendLine("                Context = Context");
            sb.AppendLine("            };");
            sb.AppendLine("            return transition;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
        }

        /// <summary>
        /// Generate all state classes
        /// </summary>
        private static void GenerateStates(FSMDefinition fsm, string outputFolder)
        {
            string statesFolder = Path.Combine(outputFolder, "States");
            string contextName = $"{fsm.MachineName}Context";

            foreach (var state in fsm.States)
            {
                GenerateState(fsm, state, statesFolder, contextName);
            }
        }

        /// <summary>
        /// Generate individual state class
        /// </summary>
        private static void GenerateState(FSMDefinition fsm, StateDefinition state, string statesFolder, string contextName)
        {
            string className = $"{state.StateName}State";
            string filePath = Path.Combine(statesFolder, $"{className}.cs");

            // Check if user file exists
            string userFilePath = Path.Combine(statesFolder, $"{className}.User.cs");
            bool hasUserFile = File.Exists(userFilePath);

            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// ============================================================================");
            sb.AppendLine($"// AUTO-GENERATED CODE - DO NOT EDIT THIS FILE");
            sb.AppendLine($"// State: {state.StateName}");
            sb.AppendLine($"// FSM: {fsm.MachineName}");
            sb.AppendLine($"// Generated: {System.DateTime.Now}");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UFSM.Core;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// State: {state.StateName}");

            if (!string.IsNullOrEmpty(state.Description))
            {
                sb.AppendLine($"    /// {state.Description}");
            }

            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public partial class {className} : StateBase<{contextName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string StateName => \"{state.StateName}\";");
            sb.AppendLine($"        public override int Priority => {state.Priority};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());

            // Create user file if it doesn't exist
            if (!hasUserFile)
            {
                CreateUserStateFile(fsm, state, statesFolder, className, contextName);
            }
        }

        private static void CreateUserStateFile(FSMDefinition fsm, StateDefinition state, string statesFolder, string className, string contextName)
        {
            string userFilePath = Path.Combine(statesFolder, $"{className}.User.cs");

            var sb = new StringBuilder();
            sb.AppendLine("// ============================================================================");
            sb.AppendLine($"// USER CODE - SAFE TO EDIT");
            sb.AppendLine($"// State: {state.StateName}");
            sb.AppendLine($"// FSM: {fsm.MachineName}");
            sb.AppendLine("// Implement your state logic here");
            sb.AppendLine("// ============================================================================");
            sb.AppendLine();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine("        public override void OnEnter()");
            sb.AppendLine("        {");
            sb.AppendLine($"            Log(\"Entered {state.StateName} state\");");
            sb.AppendLine("            // Your enter logic here");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void OnUpdate()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Your update logic here");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override void OnExit()");
            sb.AppendLine("        {");
            sb.AppendLine($"            Log(\"Exited {state.StateName} state\");");
            sb.AppendLine("            // Your exit logic here");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(userFilePath, sb.ToString());
        }

        // Helper methods
        private static string GetCSharpType(ParameterType type)
        {
            return type switch
            {
                ParameterType.Bool => "bool",
                ParameterType.Int => "int",
                ParameterType.Float => "float",
                ParameterType.String => "string",
                ParameterType.Trigger => "bool",
                _ => "object"
            };
        }

        private static string GetDefaultValue(ParameterDefinition param)
        {
            return param.Type switch
            {
                ParameterType.Bool => param.DefaultBool.ToString().ToLower(),
                ParameterType.Int => param.DefaultInt.ToString(),
                ParameterType.Float => param.DefaultFloat.ToString("F2") + "f",
                ParameterType.String => $"\"{param.DefaultString}\"",
                ParameterType.Trigger => "false",
                _ => "null"
            };
        }
    }
}